-- user table
INSERT INTO `users` VALUES('admin@mail.com','$2y$10$dNYVtiJjuJxSUHZDp.LNCuYhGEfM.Mtv2WH4g.sAJXYh5CZcjGYOy','ADMIN',false);


-- food table
INSERT INTO `food` VALUES (1,'Veg Pizza',9,'pizz.png','Veg Pizza with capsicum, onion, tomato and olives');
INSERT INTO `food` VALUES (2,'Pepperonni Pizza',10,'pizz.png','Pepperonni Pizza with capsicum, onion, tomato, olives and Pepperonni');
INSERT INTO `food` VALUES (3,'Cheese Pizza',7,'pizz.png','Pizza with cheese on it. Thats it');
INSERT INTO `food` VALUES (4,'Fried Rice',9,'rice.jpg','Vegetarian Fried Rice. Contains Eggs.');
INSERT INTO `food` VALUES (5,'Pepsi Can',5,'pepsi.jpg','Pepsi.');
INSERT INTO `food` VALUES (6,'Coca Cola',50,'coke.jpeg','Buy Pepsi Instead. Offcial Sponsor of Maryland Athletics.');
INSERT INTO `food` VALUES (7,'Veg Burger',8,'burg.jpeg','Vegetarian Burger with Potato Tikki instead of beef.');
INSERT INTO `food` VALUES (8,'Milk',3,'milk.jpeg','Straight from a cow.');
INSERT INTO `food` VALUES (9,'Coffee',4,'coffee.jpg','Milk is straight from a cow. We will provide coffee satche seperately. :)');
INSERT INTO `food` VALUES (10,'Noodles',7,'noo.jpg','Authentic Noodles.');

